version: "3"
services:
  app:
   image: "node:12-alpine"
   working_dir: /home/node/app
   volumes:
     - .:/home/node/app
   environment:
     - NODE_ENV=production
     - PORT=8080
     - HELLO_MESSAGE="Love u from Node"
   ports:
    - 80:8080
   command: "npm start"

  app2:
    image: "node:12-alpine"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=production
      - PORT=1234
      - HELLO_MESSAGE="Love u from me"
    ports:
     - 8080:1234
    command: "npm start"
